branch-defaults:
  main:
    environment: test-dev
    group_suffix: null
deploy:
  artifact: archive.zip
global:
  application_name: test
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: ECS running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
